// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: store/v1/store.proto

package storev1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSettingsResponse_SalesState int32

const (
	GetSettingsResponse_UNKNOWN     GetSettingsResponse_SalesState = 0
	GetSettingsResponse_DISABLED    GetSettingsResponse_SalesState = 1
	GetSettingsResponse_BEFORE_OPEN GetSettingsResponse_SalesState = 2
	GetSettingsResponse_OPEN        GetSettingsResponse_SalesState = 3
	GetSettingsResponse_SOLD_OUT    GetSettingsResponse_SalesState = 4
)

// Enum value maps for GetSettingsResponse_SalesState.
var (
	GetSettingsResponse_SalesState_name = map[int32]string{
		0: "UNKNOWN",
		1: "DISABLED",
		2: "BEFORE_OPEN",
		3: "OPEN",
		4: "SOLD_OUT",
	}
	GetSettingsResponse_SalesState_value = map[string]int32{
		"UNKNOWN":     0,
		"DISABLED":    1,
		"BEFORE_OPEN": 2,
		"OPEN":        3,
		"SOLD_OUT":    4,
	}
)

func (x GetSettingsResponse_SalesState) Enum() *GetSettingsResponse_SalesState {
	p := new(GetSettingsResponse_SalesState)
	*p = x
	return p
}

func (x GetSettingsResponse_SalesState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetSettingsResponse_SalesState) Descriptor() protoreflect.EnumDescriptor {
	return file_store_v1_store_proto_enumTypes[0].Descriptor()
}

func (GetSettingsResponse_SalesState) Type() protoreflect.EnumType {
	return &file_store_v1_store_proto_enumTypes[0]
}

func (x GetSettingsResponse_SalesState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetSettingsResponse_SalesState.Descriptor instead.
func (GetSettingsResponse_SalesState) EnumDescriptor() ([]byte, []int) {
	return file_store_v1_store_proto_rawDescGZIP(), []int{1, 0}
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_v1_store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_v1_store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_store_v1_store_proto_rawDescGZIP(), []int{0}
}

type GetSettingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxParticipants int64                          `protobuf:"varint,1,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	SalesDisabled   bool                           `protobuf:"varint,2,opt,name=sales_disabled,json=salesDisabled,proto3" json:"sales_disabled,omitempty"`
	SalesOpenAt     *timestamppb.Timestamp         `protobuf:"bytes,3,opt,name=sales_open_at,json=salesOpenAt,proto3" json:"sales_open_at,omitempty"`
	SalesState      GetSettingsResponse_SalesState `protobuf:"varint,4,opt,name=sales_state,json=salesState,proto3,enum=tb.store.v1.GetSettingsResponse_SalesState" json:"sales_state,omitempty"`
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_v1_store_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_v1_store_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_store_v1_store_proto_rawDescGZIP(), []int{1}
}

func (x *GetSettingsResponse) GetMaxParticipants() int64 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *GetSettingsResponse) GetSalesDisabled() bool {
	if x != nil {
		return x.SalesDisabled
	}
	return false
}

func (x *GetSettingsResponse) GetSalesOpenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SalesOpenAt
	}
	return nil
}

func (x *GetSettingsResponse) GetSalesState() GetSettingsResponse_SalesState {
	if x != nil {
		return x.SalesState
	}
	return GetSettingsResponse_UNKNOWN
}

var File_store_v1_store_proto protoreflect.FileDescriptor

var file_store_v1_store_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x62, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc7, 0x02, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6d, 0x61,
	0x78, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x0a,
	0x0e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x44, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x12, 0x3e, 0x0a, 0x0d, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x5f, 0x6f, 0x70,
	0x65, 0x6e, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x4f, 0x70,
	0x65, 0x6e, 0x41, 0x74, 0x12, 0x4c, 0x0a, 0x0b, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x74, 0x62, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x61, 0x6c, 0x65,
	0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x50, 0x0a, 0x0a, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x42,
	0x45, 0x46, 0x4f, 0x52, 0x45, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x4f, 0x50, 0x45, 0x4e, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x4f, 0x4c, 0x44, 0x5f, 0x4f,
	0x55, 0x54, 0x10, 0x04, 0x32, 0x59, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x50, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1f, 0x2e, 0x74,
	0x62, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x74, 0x62, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x1b, 0x5a, 0x19, 0x74, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f,
	0x76, 0x31, 0x3b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x76, 0x31, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_store_v1_store_proto_rawDescOnce sync.Once
	file_store_v1_store_proto_rawDescData = file_store_v1_store_proto_rawDesc
)

func file_store_v1_store_proto_rawDescGZIP() []byte {
	file_store_v1_store_proto_rawDescOnce.Do(func() {
		file_store_v1_store_proto_rawDescData = protoimpl.X.CompressGZIP(file_store_v1_store_proto_rawDescData)
	})
	return file_store_v1_store_proto_rawDescData
}

var file_store_v1_store_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_v1_store_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_store_v1_store_proto_goTypes = []interface{}{
	(GetSettingsResponse_SalesState)(0), // 0: tb.store.v1.GetSettingsResponse.SalesState
	(*GetSettingsRequest)(nil),          // 1: tb.store.v1.GetSettingsRequest
	(*GetSettingsResponse)(nil),         // 2: tb.store.v1.GetSettingsResponse
	(*timestamppb.Timestamp)(nil),       // 3: google.protobuf.Timestamp
}
var file_store_v1_store_proto_depIdxs = []int32{
	3, // 0: tb.store.v1.GetSettingsResponse.sales_open_at:type_name -> google.protobuf.Timestamp
	0, // 1: tb.store.v1.GetSettingsResponse.sales_state:type_name -> tb.store.v1.GetSettingsResponse.SalesState
	1, // 2: tb.store.v1.Store.GetSettings:input_type -> tb.store.v1.GetSettingsRequest
	2, // 3: tb.store.v1.Store.GetSettings:output_type -> tb.store.v1.GetSettingsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_store_v1_store_proto_init() }
func file_store_v1_store_proto_init() {
	if File_store_v1_store_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_store_v1_store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSettingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_store_v1_store_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSettingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_store_v1_store_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_store_v1_store_proto_goTypes,
		DependencyIndexes: file_store_v1_store_proto_depIdxs,
		EnumInfos:         file_store_v1_store_proto_enumTypes,
		MessageInfos:      file_store_v1_store_proto_msgTypes,
	}.Build()
	File_store_v1_store_proto = out.File
	file_store_v1_store_proto_rawDesc = nil
	file_store_v1_store_proto_goTypes = nil
	file_store_v1_store_proto_depIdxs = nil
}
